address review comments and add more logs
Signed-off-by: haojinming <jinming.hao@pingcap.com>

diff --git a/br/tests/utils/start_tls_tikv_cluster b/br/tests/utils/start_tls_tikv_cluster
--- a/br/tests/utils/start_tls_tikv_cluster
+++ b/br/tests/utils/start_tls_tikv_cluster
@@ -57,6 +57,6 @@ while [ $i -le $retry_times ]; do
 		exit 0
 	fi
 	let i++
-	echo "start tls tikv cluster failed"
-	exit 1
 done
+echo "start tls tikv cluster failed"
+exit 1
