[to #295] Speed up cdc integrated tests (#294)
* speed up integrated tests

Signed-off-by: pingyu <yuping@pingcap.com>

* wip

Signed-off-by: pingyu <yuping@pingcap.com>

* update release version; add usage comment for up.sh

Signed-off-by: pingyu <yuping@pingcap.com>

* print more debug info

Signed-off-by: pingyu <yuping@pingcap.com>

* fix fmt

Signed-off-by: pingyu <yuping@pingcap.com>

* add shellcheck

Signed-off-by: pingyu <yuping@pingcap.com>

* fix CI error

Signed-off-by: pingyu <yuping@pingcap.com>

* remove "br" in comment

Signed-off-by: pingyu <yuping@pingcap.com>

* remove useless cdc target

Signed-off-by: pingyu <yuping@pingcap.com>

Signed-off-by: pingyu <yuping@pingcap.com>
Signed-off-by: zeminzhou <zhouzemin@pingcap.com>

diff --git a/cdc/tests/integration_tests/_utils/start_tidb_cluster_impl b/cdc/tests/integration_tests/_utils/start_tidb_cluster_impl
--- a/cdc/tests/integration_tests/_utils/start_tidb_cluster_impl
+++ b/cdc/tests/integration_tests/_utils/start_tidb_cluster_impl
@@ -11,6 +11,7 @@ tidb_config=
 pd_config=
 multiple_upstream_pd=
 random_file_name=
+verify_tidb=false
 
 # Random generate the sockets config.
 # Make sure we dont use the same sock.
@@ -42,6 +43,9 @@ while [[ ${1} ]]; do
 	--multiple-upstream-pd)
 		multiple_upstream_pd=${2}
 		shift
+		;;
+	--verify-tidb)
+		vierfy_tidb=true
 		;;
 	*)
 		echo "Unknown parameter: ${1}" >&2
@@ -209,7 +213,20 @@ tikv-server \
 	-C "$OUT_DIR/tikv-config.toml" \
 	-s "$OUT_DIR/tikv_down" &
 
-sleep 2
+ensure_tikv() {
+	PD_ADDR=$1
+	echo "Waiting initializing TiKV..."
+	while ! run_curl "http://$PD_ADDR/pd/api/v1/cluster/status" | grep '"is_initialized": true'; do
+		i=$((i + 1))
+		if [ "$i" -gt 20 ]; then
+			echo 'Failed to initialize TiKV cluster'
+			return 1
+		fi
+		sleep 1
+	done
+}
+ensure_tikv "${UP_PD_HOST_1}:${UP_PD_PORT_1}"
+ensure_tikv "${DOWN_PD_HOST}:${DOWN_PD_PORT}"
 
 echo "Starting Upstream TiDB..."
 randomGenSocketsConf
@@ -231,27 +248,30 @@ tidb-server \
 	--status=${DOWN_TIDB_STATUS} \
 	--log-file "$OUT_DIR/tidb_down.log" &
 
-echo "Verifying Upstream TiDB is started..."
-i=0
-while ! mysql -uroot -h${UP_TIDB_HOST} -P${UP_TIDB_PORT} --default-character-set utf8mb4 -e 'select * from mysql.tidb;'; do
-	i=$((i + 1))
-	if [ "$i" -gt 60 ]; then
-		echo 'Failed to start upstream TiDB'
-		exit 2
-	fi
-	sleep 2
-done
+# Skip verify tidb to speed up
+if [ "$verify_tidb" = true ]; then
+	echo "Verifying Upstream TiDB is started..."
+	i=0
+	while ! mysql -uroot -h${UP_TIDB_HOST} -P${UP_TIDB_PORT} --default-character-set utf8mb4 -e 'select * from mysql.tidb;'; do
+		i=$((i + 1))
+		if [ "$i" -gt 60 ]; then
+			echo 'Failed to start upstream TiDB'
+			exit 2
+		fi
+		sleep 2
+	done
 
-echo "Verifying Downstream TiDB is started..."
-i=0
-while ! mysql -uroot -h${DOWN_TIDB_HOST} -P${DOWN_TIDB_PORT} --default-character-set utf8mb4 -e 'select * from mysql.tidb;'; do
-	i=$((i + 1))
-	if [ "$i" -gt 60 ]; then
-		echo 'Failed to start downstream TiDB'
-		exit 1
-	fi
-	sleep 2
-done
+	echo "Verifying Downstream TiDB is started..."
+	i=0
+	while ! mysql -uroot -h${DOWN_TIDB_HOST} -P${DOWN_TIDB_PORT} --default-character-set utf8mb4 -e 'select * from mysql.tidb;'; do
+		i=$((i + 1))
+		if [ "$i" -gt 60 ]; then
+			echo 'Failed to start downstream TiDB'
+			exit 1
+		fi
+		sleep 2
+	done
+fi
 
 echo "Starting CDC state checker..."
 if ! command -v cdc_state_checker &>/dev/null; then
