[to #381] Add more integration tests for Kafka sink (#387)
* kafka consumer tolerate TiKV errors

Signed-off-by: Ping Yu <yuping@pingcap.com>

* polish

Signed-off-by: Ping Yu <yuping@pingcap.com>

* improve download

Signed-off-by: Ping Yu <yuping@pingcap.com>

* fix no wget

Signed-off-by: Ping Yu <yuping@pingcap.com>

* trap kafka consumer log on exit

Signed-off-by: Ping Yu <yuping@pingcap.com>

* more logs

Signed-off-by: Ping Yu <yuping@pingcap.com>

* more memory usage for kafka sink

Signed-off-by: Ping Yu <yuping@pingcap.com>

* trigger CI

Signed-off-by: Ping Yu <yuping@pingcap.com>

* skip error on memory oversize for Kafka sink

Signed-off-by: Ping Yu <yuping@pingcap.com>

* longer check_sync_diff timeout

Signed-off-by: Ping Yu <yuping@pingcap.com>

* check event nil

Signed-off-by: Ping Yu <yuping@pingcap.com>

---------

Signed-off-by: Ping Yu <yuping@pingcap.com>

diff --git a/cdc/tests/integration_tests/_utils/test_prepare b/cdc/tests/integration_tests/_utils/test_prepare
--- a/cdc/tests/integration_tests/_utils/test_prepare
+++ b/cdc/tests/integration_tests/_utils/test_prepare
@@ -66,3 +66,20 @@ function get_kafka_sink_uri() {
 function stop_kafka_consumer() {
 	cleanup_process cdc_kafka_consumer
 }
+
+# Usage: trap 'on_exit $? $LINENO $SINK_TYPE $WORK_DIR' EXIT
+function on_exit() {
+	STATUS_CODE=$1
+	LINE=$2
+	SINK_TYPE=$3
+	WORK_DIR=$4
+
+	stop_tidb_cluster
+
+	if [ "$STATUS_CODE" = "0" ]; then
+		return 0
+	else
+		echo "Error $STATUS_CODE occurred on $LINE for sink $SINK_TYPE"
+		tail -n +1 "$WORK_DIR"/cdc*.log
+	fi
+}
