[to #67] fix rawkv backup failure (#77)
* br: cherry pick tidb#32612 to fix rawkv backup failure

Issue Number: #67

Signed-off-by: pingyu <yuping@pingcap.com>

* revert unnecessary port change

Signed-off-by: pingyu <yuping@pingcap.com>

* migrate test logics from run.sh to run.py

Signed-off-by: pingyu <yuping@pingcap.com>

* temporarily disable old versions < 6.0

Signed-off-by: pingyu <yuping@pingcap.com>

* separate CI of 5.X versions

Signed-off-by: pingyu <yuping@pingcap.com>

* bugfix

Signed-off-by: pingyu <yuping@pingcap.com>

* bugfix

Signed-off-by: pingyu <yuping@pingcap.com>

* address comments

Signed-off-by: pingyu <yuping@pingcap.com>

* tiny fix

Signed-off-by: pingyu <yuping@pingcap.com>

diff --git a/.github/workflows/ci-br.yml b/.github/workflows/ci-br.yml
--- a/.github/workflows/ci-br.yml
+++ b/.github/workflows/ci-br.yml
@@ -64,7 +64,35 @@ jobs:
     runs-on: ubuntu-latest
     strategy:
       matrix:
-        tikv_version: [v5.0.0, v5.1.0, v5.2.0, v5.3.0, v5.4.0, v6.0.0, nightly]
+        tikv_version: [v6.0.0, nightly]
+    steps:
+      - uses: actions/checkout@v2
+      - uses: actions/setup-go@v2
+        with:
+          go-version: '1.16.1'
+      - name: install tiup
+        run: curl --proto '=https' --tlsv1.2 -sSf https://tiup-mirrors.pingcap.com/install.sh | sh
+      - name: start tikv cluster
+        run: |
+          # start tikv in apiv1ttl
+          /home/runner/.tiup/bin/tiup playground ${{ matrix.tikv_version }} --mode tikv-slim --kv 1 --without-monitor --kv.config /home/runner/work/migration/migration/.github/config/br_rawkv.toml --pd.config /home/runner/work/migration/migration/.github/config/br_pd.toml &> raw.out 2>&1 &
+          # The first run of `tiup` has to download all components so it'll take longer.
+          sleep 1m 30s
+          # Parse PD address from `tiup` output
+          echo "PD_ADDR=$(cat raw.out | grep -oP '(?<=PD client endpoints: \[)[0-9\.:]+(?=\])')" >> $GITHUB_ENV
+          # Log the output
+          echo "$(cat raw.out)" >&2
+      - name: run integration test
+        run: |
+          cd br
+          make test/integration
+  br-integration-test-5X:
+    # Separate integration tests of v5.X, to distinguish whether failure would be caused by compatibility of old versions.
+    name: br-integration-test-5X-${{ matrix.tikv_version }}
+    runs-on: ubuntu-latest
+    strategy:
+      matrix:
+        tikv_version: [v5.0.0, v5.1.0, v5.2.0, v5.3.0, v5.4.0]
     steps:
       - uses: actions/checkout@v2
       - uses: actions/setup-go@v2
